export type TanachBook = {
  order: number;
  name: string;
};

export const TANACH_BOOKS: TanachBook[] = [
  { order: 1, name: 'Genesis' },
  { order: 2, name: 'Exodus' },
  { order: 3, name: 'Leviticus' },
  { order: 4, name: 'Numbers' },
  { order: 5, name: 'Deuteronomy' },
  { order: 6, name: 'Joshua' },
  { order: 7, name: 'Judges' },
  { order: 8, name: '1 Samuel' },
  { order: 9, name: '2 Samuel' },
  { order: 10, name: '1 Kings' },
  { order: 11, name: '2 Kings' },
  { order: 12, name: 'Isaiah' },
  { order: 13, name: 'Jeremiah' },
  { order: 14, name: 'Ezekiel' },
  { order: 15, name: 'Hosea' },
  { order: 16, name: 'Joel' },
  { order: 17, name: 'Amos' },
  { order: 18, name: 'Obadiah' },
  { order: 19, name: 'Jonah' },
  { order: 20, name: 'Micah' },
  { order: 21, name: 'Nahum' },
  { order: 22, name: 'Habakkuk' },
  { order: 23, name: 'Zephaniah' },
  { order: 24, name: 'Haggai' },
  { order: 25, name: 'Zechariah' },
  { order: 26, name: 'Malachi' },
  { order: 27, name: 'Psalms' },
  { order: 28, name: 'Proverbs' },
  { order: 29, name: 'Job' },
  { order: 30, name: 'Song of Songs' },
  { order: 31, name: 'Ruth' },
  { order: 32, name: 'Lamentations' },
  { order: 33, name: 'Ecclesiastes' },
  { order: 34, name: 'Esther' },
  { order: 35, name: 'Daniel' },
  { order: 36, name: 'Ezra' },
  { order: 37, name: 'Nehemiah' },
  { order: 38, name: '1 Chronicles' },
  { order: 39, name: '2 Chronicles' },
];
